---
networks:
  default:
  dev-proxy:
    external: true

volumes:
  db-data:
  pg-data:
  rds-data:
  elastic-data:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile.loc
      args:
        ENABLE_XDEBUG: ${ENABLE_XDEBUG:-true}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      STAND: loc
      PHP_IDE_CONFIG: serverName=${VIRTUAL_HOST}
      APP_URL: http://${VIRTUAL_HOST}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-tmp}
      DB_NAME: ${DB_NAME:-laravel}
      PG_HOST: ${PG_HOST:-postgres}
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER:-postgres}
      PG_PASS: ${PG_PASS:-tmp}
      PG_NAME: ${PG_NAME:-laravel}
      ELASTIC_HOST: ${ELS_HOST:-elasticsearch}
      ELASTIC_PORT: ${ELS_PORT:-9200}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    volumes:
      - ./app:/var/www/html
      - ./.git:/var/www/html/.git:ro
    networks:
      - default
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-php.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-php.loadbalancer.server.port=80"
    depends_on:
      - db
      - redis
      - elasticsearch
    restart: unless-stopped

#  swoole:
#    build:
#      context: .
#      dockerfile: ./docker/images/php/Dockerfile.loc
#      args:
#        ENABLE_XDEBUG: ${ENABLE_XDEBUG:-true}
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
#    environment:
#      STAND: loc
#      APP_URL: http://${VIRTUAL_HOST}
#      DB_HOST: ${DB_HOST:-db}
#      DB_PORT: ${DB_PORT:-3306}
#      DB_USER: ${DB_USER:-root}
#      DB_PASS: ${DB_PASS:-tmp}
#      DB_NAME: ${DB_NAME:-laravel}
#      PG_HOST: ${PG_HOST:-postgres}
#      PG_PORT: ${PG_PORT:-5432}
#      PG_USER: ${PG_USER:-postgres}
#      PG_PASS: ${PG_PASS:-tmp}
#      PG_NAME: ${PG_NAME:-laravel}
#      ELASTIC_HOST: ${ELS_HOST:-elasticsearch}
#      ELASTIC_PORT: ${ELS_PORT:-9200}
#      REDIS_HOST: ${REDIS_HOST:-redis}
#      REDIS_PORT: ${REDIS_PORT:-6379}
#    command: ["php", "artisan", "octane:start", "--host=0.0.0.0", "--workers=10"]
#    volumes:
#      - ./app:/var/www/html
#      - ./.git:/var/www/html/.git:ro
#    networks:
#      - default
#      - dev-proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=dev-proxy"
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-swoole.rule=Host(`swoole-${VIRTUAL_HOST}`)"
#      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-swoole.loadbalancer.server.port=8000"
#    depends_on:
#      - db
#      - redis
#      - elasticsearch
#    restart: unless-stopped

  postgres:
      image: postgres:16-alpine
      security_opt:
          - no-new-privileges:true
      tmpfs:
          - /tmp
          - /var/run/postgresql
      volumes:
          - pg-data:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: ${PG_PASS:-tmp}
          POSTGRES_DB: ${PG_DBNAME:-laravel}
      restart: unless-stopped

  pgadmin:
      image: dpage/pgadmin4
      depends_on:
          - db
      environment:
          PGADMIN_DEFAULT_EMAIL: "pga@astrio.net"
          PGADMIN_DEFAULT_PASSWORD: "admin123"
      networks:
          - default
          - dev-proxy
      labels:
          - "traefik.enable=true"
          - "traefik.docker.network=dev-proxy"
          - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-pga.rule=Host(`pga-${VIRTUAL_HOST}`)"
          - "traefik.http.services.${COMPOSE_PROJECT_NAME}-pga.loadbalancer.server.port=5050"
      restart: unless-stopped


  db:
    image: mariadb:12.1
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS:-tmp}
        MYSQL_DATABASE: ${DB_NAME:-laravel}
        MARIADB_AUTO_UPGRADE: 1
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    volumes:
      - rds-data:/data
    restart: unless-stopped

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_USER: ${DB_USER:-root}
      PMA_PASSWORD: ${DB_PASS:-tmp}
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1047527424
    expose:
      - 80
    networks:
      - default
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-pma.rule=Host(`pma-${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-pma.loadbalancer.server.port=80"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HEAP_SIZE=512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

    # ---------- RabbitMQ ----------
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      hostname: rabbitmq-${VIRTUAL_HOST}   # опционально, имя внутри контейнера
      environment:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: password
      volumes:
          - ./docker/rabbitmq_data:/var/lib/rabbitmq   # сохраняем данные локально
      networks:
          default:
              aliases:
                  - rabbitmq-${VIRTUAL_HOST}   # чтобы контейнеры в сети видели его по этому имени
          dev-proxy:                       # подключаем к сети Traefik
      labels:
          - "traefik.enable=true"
          - "traefik.docker.network=dev-proxy"
          # Веб-интерфейс (порт 15672)
          - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rabbitmq.rule=Host(`rabbitmq-${VIRTUAL_HOST}`)"
          - "traefik.http.services.${COMPOSE_PROJECT_NAME}-rabbitmq.loadbalancer.server.port=15672"
      restart: unless-stopped

    # ---------- Kafka (KRaft) ----------
  kafka:
      image: apache/kafka:latest
      container_name: kafka
      hostname: kafka-${VIRTUAL_HOST}    # опционально
      ports:
          - "9092:9092"                     # проброс на хост (опционально, см. пояснение ниже)
      environment:
          # Настройки KRaft (без ZooKeeper)
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
          # !!! Важно: рекламируемый адрес, который увидят клиенты
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-${VIRTUAL_HOST}:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_LOG_DIRS: /var/lib/kafka/data
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      volumes:
          - ./docker/kafka_data:/var/lib/kafka/data   # сохраняем данные
      networks:
          default:
              aliases:
                  - kafka-${VIRTUAL_HOST}   # чтобы контейнеры в сети видели его по этому имени
          dev-proxy:                     # подключаем к сети Traefik (хотя для Kafka HTTP не нужен)
      restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile.loc
      args:
        ENABLE_XDEBUG: ${ENABLE_XDEBUG:-true}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      STAND: loc
      PHP_IDE_CONFIG: serverName=${VIRTUAL_HOST}
      APP_URL: http://${VIRTUAL_HOST}
      DB_HOST: ${DB_HOST:-postgre}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-tmp}
      DB_NAME: ${DB_NAME:-laravel}
      PG_HOST: ${PG_HOST:-postgres}
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER:-postgres}
      PG_PASS: ${PG_PASS:-tmp}
      PG_NAME: ${PG_NAME:-laravel}
      ELASTIC_HOST: ${ELS_HOST:-elasticsearch}
      ELASTIC_PORT: ${ELS_PORT:-9200}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    volumes:
      - ./app:/var/www/html
      - ./.git:/var/www/html/.git:ro
    networks:
      - default
      - dev-proxy
    command: ["php", "artisan", "queue:work", "--queue=notifications", "--sleep=3", "--tries=3"]
    depends_on:
      - db
      - redis
      - postgres
      - rabbitmq
    restart: unless-stopped
